### ISSUE TITLE
README.md Improvements

### ISSUE THREAD

**Issue by hemantwasthere** [hemantwasthere/GitHub-Clone#12]
Link to the README.md -> https://github.com/hemantwasthere/GitHub-Clone/blob/main/README.md

* Mention contribution guidelines
* Add more images and gifs to project it better
* Fix some typos if any

**Comment by SJ-Kumar** [comment]
Assign it to me...I can cleanup your readme. You can select few tasks from my repo as well.

**Comment by SJ-Kumar** [comment]
Added contributing.md file. accept my pull request.

**Comment by SJ-Kumar** [comment]
![image](https://user-images.githubusercontent.com/90379900/193407211-7745c91c-8ed9-441c-94c4-0e0f3e503a15.png)
